// Generated by CoffeeScript 1.9.3
(function() {
  var exports, sendMessageById, slack;

  slack = require('../slackClient');

  sendMessageById = function(id, message) {
    var channel;
    channel = slack.getChannelGroupOrDMByID(id);
    return channel.send(message);
  };

  exports = this;

  exports.sendMessageById = sendMessageById;

}).call(this);
