// Generated by CoffeeScript 1.9.3
(function() {
  var exports, sendMessage, sendMessageById, slack;

  slack = require('../slackClient');

  sendMessageById = function(id, message) {
    var channel;
    channel = slack.getChannelGroupOrDMByID(id);
    return sendMessage(channel, message);
  };

  sendMessage = function(channel, message) {
    return channel.send(message);
  };

  exports = this;

  exports.sendMessageById = sendMessageById;

  exports.sendMessage = sendMessage;

}).call(this);
