// Generated by CoffeeScript 1.9.3
(function() {
  var exports, sendMessageByUserName, slack;

  slack = require('../slackClient');

  sendMessageByUserName = function(userName, message) {
    var channel, dm;
    dm = slack.getDMByName(userName);
    channel = slack.getChannelGroupOrDMByID(dm.id);
    return channel.send(message);
  };

  exports = this;

  exports.sendMessageByUserName = sendMessageByUserName;

}).call(this);
