// Generated by CoffeeScript 1.9.3
(function() {
  var exports, generate, getRandomInt, names;

  names = ["jobby gobler", "kitten cooker", "douche knuckle", "satchel man", "heinous chicken puncher", "bum-licking smeghead", "hog humper", "full-gorged codpiece", " muddy-mottled bag of guts", "swag-bellied punk", "long-tongued plebian", "shard-borne drunkard"];

  generate = function() {
    var randomIndex;
    randomIndex = getRandomInt(0, names.length);
    return names[randomIndex];
  };

  getRandomInt = function(min, max) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
  };

  exports = this;

  exports.generate = generate;

}).call(this);
