// Generated by CoffeeScript 1.10.0
(function() {
  var isNumeric;

  isNumeric = function(number) {
    var matches;
    matches = number.match(/\d+/g);
    return matches !== null;
  };

  module.exports = isNumeric;

}).call(this);
