// Generated by CoffeeScript 1.9.3
(function() {
  var exports, getUserName, isNumeric, slack;

  slack = require('../slackClient');

  isNumeric = require('./isNumeric');

  getUserName = function(userId) {
    var user;
    if (!isNumeric(userId)) {
      return userId;
    }
    user = slack.getUserByID(userId);
    return user.name;
  };

  exports = this;

  exports.getUserName = getUserName;

}).call(this);
