// Generated by CoffeeScript 1.10.0
(function() {
  var channel, exports, getFromMessage, sendErrorMessage;

  channel = require('./channel');

  getFromMessage = function(message) {
    var split;
    split = message.text.split(' <@');
    if (split.length < 2) {
      sendErrorMessage(message);
      return false;
    }
    return split[1].replace('>', '');
  };

  sendErrorMessage = function(message) {
    var messageText;
    messageText = "I don't think you supplied the user name, muppet!";
    return channel.sendMessageById(message.channel, messageText);
  };

  exports = this;

  exports.getFromMessage = getFromMessage;

}).call(this);
