adjectives = [
  "jobby"
  "kitten"
  "douche"
  "satchel"
  "heinous"
  "bum-licking"
  "full-gorged"
  "muddy-mottled"
  "swag-bellied"
  "long-tongued"
  "shard-borne"
  "bad tempered"
  "aggravating"
  "aromatic"
  "authentic"
  "awesome"
  "bewitched"
  "biodegradable"
  "calculating"
  "corrupt"
  "cylindrical"
  "dangerous"
  "dazzling"
  "deficient"
  "delicious"
  "demanding"
  "disastrous"
  "edible"
  "fragrant"
  "gaseous"
  "glorious"
  "graceful"
  "grouchy"
  "growling"
  "gruesome"
  "humming"
  "illiterate"
  "infantile"
  "jam-packed"
  "kaleidoscopic"
  "kooky"
  "majestic"
  "salty"
  "scientific"
  "shameless"
  "sniveling"
  "suspicious"
  "villainous"
  "well-documented"
  "yellowish"
  "zesty"
  "cheese eating"
]

nouns = [
  "chicken puncher"
  "smeghead"
  "blunderbus"
  "codpiece"
  "punk"
  "plebian"
  "drunkard"
  "didgeridoo"
  "hornswoggle"
  "wombat"
  "double fault"
  "eskimo"
  "extremity"
  "lettuce"
  "weed wacker"
  "polar bear"
  "totempole"
  "lieutenant governor"
  "refrigerator"
  "railroad worm"
  "french chef"
  "scourge upon the earth"
  "fairy lantern"
  "space invader"
  "unicorn"
  "potato"
  "thingumajig"
  "broccoli"
  "surrender monkey"
  "pilot inspector"
  "tory voter"
  "snake eater"
  "post stamp collector"
  "monkey creeper"
  "window peeper"
  "brain eater"
  "plate licker"
  "toiler seat"
  "remotely controlled foot massager"
  "fly researching assistant"
  "IT professional"
]

generate = ->
  randomAdjectiveIndex = getRandomInt 0, adjectives.length - 1
  randomNounIndex = getRandomInt 0, nouns.length - 1
  name = "#{adjectives[randomAdjectiveIndex]} #{nouns[randomNounIndex]}"
  return name

getRandomInt = (min, max) ->
  return Math.floor(Math.random() * (max - min + 1)) + min


exports = this
exports.generate = generate
