// Generated by CoffeeScript 1.9.3
(function() {
  var annoyUser, directMessage, exports, horribleNameGenerator, slack;

  slack = require('./slackClient');

  directMessage = require('./services/directMessage');

  horribleNameGenerator = require('./services/horribleNameGenerator');

  annoyUser = function(userName) {
    var horrbileName, message;
    horrbileName = horribleNameGenerator.generate();
    message = "Hey you " + horrbileName + "!";
    directMessage.sendMessageByUserName(userName, message);
    return console.log("message " + message + " sent to " + userName);
  };

  exports = this;

  exports.annoyUser = annoyUser;

}).call(this);
