// Generated by CoffeeScript 1.9.3
(function() {
  var annoy, shouldIAnnoy, slack, userToAnnoy;

  slack = require('./slackClient');

  shouldIAnnoy = require('./shouldIAnnoy');

  annoy = require('./annoy');

  userToAnnoy = '';

  slack.on('open', function() {
    return console.log("Connected to " + slack.team.name + " as @" + slack.self.name);
  });

  slack.on('message', function(message) {
    var shouldIAnnoyCurrentUser;
    shouldIAnnoyCurrentUser = shouldIAnnoy.shouldIAnnoyUser(message);
    if (shouldIAnnoyCurrentUser) {
      userToAnnoy = shouldIAnnoyCurrentUser;
      return annoy.annoyUser(userToAnnoy);
    }
  });

  slack.on('error', function(err) {
    return console.error("Error", err);
  });

  slack.login();

}).call(this);
