// Generated by CoffeeScript 1.10.0
(function() {
  var channel, exports, getUserId, shouldIAnnoyUser, slack, userNameRetriever, userService, whoWeGoingToAnnoy;

  slack = require('./slackClient');

  userService = require('./services/user');

  channel = require('./services/channel');

  userNameRetriever = require('./services/userNameRetriever');

  shouldIAnnoyUser = function(message) {
    if (message.text.match('annoy')) {
      return getUserId(message);
    } else {
      return false;
    }
  };

  getUserId = function(message) {
    var userId, userName;
    if (userId = userNameRetriever.getFromMessage(message)) {
      userName = userService.getUserName(userId);
      whoWeGoingToAnnoy(message, userName);
      return userName;
    }
  };

  whoWeGoingToAnnoy = function(message, userName) {
    var messageText;
    if (userName) {
      messageText = "I'm off to annoy " + userName;
    } else {
      messageText = "I can't find the blighter.";
    }
    return channel.sendMessageById(message.channel, messageText);
  };

  exports = this;

  exports.shouldIAnnoyUser = shouldIAnnoyUser;

}).call(this);
