// Generated by CoffeeScript 1.9.3
(function() {
  var channel, exports, getUserNameFromMessage, reply, shouldIAnnoyUser, slack, userService, whoWeGoingToAnnoy;

  slack = require('./slackClient');

  userService = require('./services/user');

  channel = require('./services/channel');

  shouldIAnnoyUser = function(message) {
    var userId, userName;
    if (message.text.match('annoy')) {
      userId = getUserNameFromMessage(message);
      if (userId) {
        userName = userService.getUserName(message.user);
        whoWeGoingToAnnoy(message, userName);
        return userName;
      } else {
        return false;
      }
    } else {
      return false;
    }
  };

  getUserNameFromMessage = function(message) {
    var split;
    split = message.text.split(' <@');
    if (split.length < 2) {
      reply(message, "I don't think you supplied the user name, muppet!");
    }
    return split[1];
  };

  reply = function(message, messageText) {
    return channel.sendMessageById(message.channel, messageText);
  };

  whoWeGoingToAnnoy = function(message, userName) {
    var messageText;
    messageText = "I'm off to annoy " + userName;
    return reply(message, messageText);
  };

  exports = this;

  exports.shouldIAnnoyUser = shouldIAnnoyUser;

}).call(this);
