// Generated by CoffeeScript 1.9.3
(function() {
  var Slack, autoMark, autoReconnect, slack, slackToken;

  Slack = require('slack-client');

  slackToken = 'xoxb-12762509828-bgL0ZsbfYIHKcbjM13EcXcH9';

  autoReconnect = true;

  autoMark = true;

  slack = new Slack(slackToken, autoReconnect, autoMark);

  module.exports = slack;

}).call(this);
